#! /bin/sh

DIR_SRC="../src"
DIR_DEST="/usr/local/bin"

if [[ "root" != `whoami` ]]; then
    echo "Please execute using the sudo command."
    exit 1;
fi

cd "$(dirname "$0")"

cp $DIR_SRC/saltout.py $DIR_DEST/saltout

